---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgAD57QVrCcQghjlAHZyxcO9ln6c9ViUMuUWG28zudqICh1LjxHxk2lRLwMKdkOT6Jkw+rDaTAc3L/2eRfVslnEFd//csIrhCW4REDE6vmaDUsBmsIh1/LJEI+FJucCaG5Rzyad9wVXfAxRpvE4TjnU63y+RXZcKSMzH/L9e8WVMIRfeBDh8SHgOdCXQd4NLvTxpz9v1Wr88/ISiPIPRnT0tOhOi0cqlMCRrpQrWvVBdx/V5gZ0uXJEwCKMQB5OLQsP4fEK53OEsmi3A0rHuxxBXDO7nmCzVwVgs35pG5pjMAp2PQP2/So2Qd4Z3SrJgZl2GROc3xY1M5N+xS7Coy9Vba3CwGxBllA4+gqRnXnhOAuz9Kp/vvWK18u6YqNc/IlV3Xpf1lrUPSr9j+nesCaeINpq9u8FYLepylplwAjdGIBAFBiw1eO1I3xzN0QLOMtvuYQiP8DNXzZrzLI2van4QZT77azRx6506qJTrYzpbXO4YpMblPZLvMPfw3GPHT5jQd70h9H6bmi+njVD+wglBcE6mAoyGyXehtbPM+amx5PpFUHpaM6hTApySbPNkEF8dEWW+iYOqSTnCIR0C5Tpi4UoKXEpD/FVXsgdpg0C6983JRiJbUqaewiFP0UganyK1kdJPzk3vMAviPrOcwIDhDSzAogzRZQHkKD/YMcYP7/gWWtAENWBm01UmcaQ1vjjL6JZSFrcgX5A=
    user: AgCApf8Kcc4LJnDJvFAxm+dNy/YPiPjI4SuUY2dXKXd6QDXl50rTQEhuFhzlu0AeWF0xuduoqin9Rtv3T6YTOUMMaAMfSbKW6K3EqhfvAbxmepiAdN11TPjWh/SuDxmLgu7jJOynaLs4Lor8QtZOmzcuhysBn3oOWQi4IdGzzOJNbx4i7F3QlBKxdkZTGRPX0QpT/WeLzJLO8PcfxGhHJIq94Zov5//GzfGY3XFHtrZ9y2HFETqBM423sWchg3Koto3g5qOm+b2tAm8U2u5suSwPrV3yJcTscbEtGj5KoS+W+zDPvLWeWO8+WDh/4XR8UhBfrb37t0+xrvyi47g2k7AGO+xSifb3S5EV73W1dwXCfPamLYauroDmd6TxruU0oudmfeaTs1ZcFNh7SfnVJE4jL5ECvVuNP0J4s1G/dsff6/W1uE72b1Cj3RxTju5PRTt6aW64dhfSQpz4NgqpaQ/czkAItVof4e/MRhnlQJXxo/91jDjx0rdAw9oN0zJUWw2rVkOg3W7YVrtAnaVlq+zDdJFiIZtPZzah1SdMDoa/lv36RHmztsvKO2hwf4rEzdz0qjbrIqT1U29e0z14ZzlytfROt8CPIWrKuTacRDeYJehpyfcTilrCLgOScywl+3QP5cpE5Ny+Uk+oqi5/EhnkSvYUn8VPNjjEhR3OfyGCCJ8zKBTxyg/6ZtP5o/Bhah2JGxF2Wg==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default
